steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/base:latest', '-f', 'dockerfiles/GCP/BaseDockerfile', '.' ]
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/base:latest'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _LOCATION: us
  _REPOSITORY: kohya-ss
